# fly.toml app configuration file generated for chgk-bot on 2023-09-12T12:33:48+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "chgk-bot"
primary_region = "ams"

[deploy]
  strategy = "rolling"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
